var ID_PROFILE_FOLDER        = '1qHogROhRBOxUZOWTB7_4mZTSBg0ntJQK';
var ID_PROFILE_FOLDER_ALL    = '1Ovu2R4O-FghEQTFaGC8hxSFUuWmONnms';
var ID_PROFILE_FOLDER_CLOSED = '1ydVJ5kl5z6uae6X-4W2OhplZy5ODEtjq';
var ID_PROFILE_FOLDER_LOYAL  = '1D3oyZMQdwEgSRfLO4l5pMh1ixsM6ni_C';
var ID_PROFILE_FOLDER_BANNED = '17ucR54mW-SQn71V3MubXHpV9DGG2muGY';
var ID_PROFILE_FOLDER_HIRED  = '1B0UKfd5M8YB6KTwREzR1rYTILKiEUhjn';
var ID_PROFILE_FOLDER_FIRED  = '1qdK_wyFWprWEW2mc0KT_3G4GJGt-9mnh';


var ID_RESUME_FOLDER  = '1L124hWoMDbpse9zmTQospWoGE6ea0AVQ';

var ID_PROFILE_TEMPLATE = '18mx-omQFvXAswelYaB1ziNZRvIeUmVZKwkG75_yZQ8g';

var ADDR_RESUME_F_NAME  = ['bio', 1, 1];
var ADDR_RESUME_S_NAME  = ['bio', 2, 1];
var ADDR_RESUME_EMAIL   = ['bio', 3, 1];
var ADDR_RESUME_PHONE   = ['bio', 4, 1];
var ADDR_RESUME_LETTER  = ['bio', 5, 1];
var ADDR_RESUME_RESUME  = ['bio', 6, 1];
var ADDR_RESUME_PASWRD  = ['bio', 7, 1];